/**
 * Dish-image PROVIDER SEAM.
 *
 * One narrow interface ({@link ImageProvider}) with two implementations:
 *  - Imagen 4 Fast on Vertex AI (`imagen-4.0-fast-generate-001`, EU region) — DEFAULT.
 *  - FLUX.1 [schnell] on Workers AI — on-platform FALLBACK.
 *
 * The route picks the configured primary, then transparently falls back to FLUX
 * when the primary is unconfigured (no Vertex creds — e.g. local `wrangler dev` /
 * tests) or fails at call time. This keeps the route runnable with NO keys while
 * defaulting to Imagen in production once creds are set.
 *
 * ANONYMITY (SECURITY.md §1): a provider receives ONLY the dish name (a menu string)
 * built into a static prompt. No user data is templated into either provider.
 *
 * AI-ACT (SECURITY.md §2.C): every generated image is marked AI-generated by the
 * route. Each provider reports a short `model` label that is stored as R2
 * provenance metadata alongside the bytes.
 */
import type { Env } from '../env';

/** Workers AI text-to-image model — FLUX.1 [schnell], on-platform (INFRASTRUCTURE.md). */
export const FLUX_MODEL = '@cf/black-forest-labs/flux-1-schnell';
/** Vertex AI Imagen 4 Fast model id (pinned — never "latest"). */
export const IMAGEN_MODEL = 'imagen-4.0-fast-generate-001';

/** Short label stored as R2 provenance for a FLUX-generated image. */
export const FLUX_LABEL = 'flux-1-schnell';
/** Short label stored as R2 provenance for an Imagen-generated image. */
export const IMAGEN_LABEL = 'imagen-4.0-fast';

/** Provider identifiers used in config + selection. */
export type ImageProviderId = 'wavespeed' | 'imagen' | 'flux';

/** WaveSpeed API base; the model id is appended as the path (see {@link makeWavespeedProvider}). */
export const WAVESPEED_BASE_URL = 'https://api.wavespeed.ai/api/v3';
/** Default WaveSpeed model when WAVESPEED_MODEL is unset — a fast FLUX schnell. */
export const WAVESPEED_DEFAULT_MODEL = 'wavespeed-ai/flux-schnell';

/** The result of one generation: PNG bytes + the model label for provenance. */
export interface GeneratedImage {
  bytes: Uint8Array<ArrayBuffer>;
  /** Short model label persisted to R2 `customMetadata.model`. */
  modelLabel: string;
}

/** A single dish-image generator behind the seam. */
export interface ImageProvider {
  readonly id: ImageProviderId;
  /** True only when this provider has everything it needs to run (creds/bindings). */
  isConfigured(env: Env): boolean;
  /** Generate one PNG for the static prompt. Throws on any provider failure. */
  generate(prompt: string, env: Env): Promise<GeneratedImage>;
}

/**
 * Decode a base64 string (e.g. Imagen `bytesBase64Encoded`, or a FLUX `image`
 * field) into PNG bytes.
 */
function base64ToBytes(base64: string): Uint8Array<ArrayBuffer> {
  const binary = atob(base64);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i += 1) {
    bytes[i] = binary.charCodeAt(i);
  }
  return bytes;
}

/**
 * Normalize the several shapes Workers AI may return (base64 `image`, a
 * `ReadableStream`, an `ArrayBuffer`, or a `Uint8Array`) into PNG bytes.
 */
async function workersAiToBytes(result: unknown): Promise<Uint8Array<ArrayBuffer>> {
  if (result instanceof ReadableStream) {
    return new Uint8Array(await new Response(result).arrayBuffer());
  }
  if (result instanceof ArrayBuffer) {
    return new Uint8Array(result);
  }
  if (result instanceof Uint8Array) {
    // Copy into a fresh ArrayBuffer-backed view (source may be SharedArrayBuffer-backed).
    return new Uint8Array(result.slice().buffer);
  }
  if (
    typeof result === 'object' &&
    result !== null &&
    'image' in result &&
    typeof (result as { image: unknown }).image === 'string'
  ) {
    return base64ToBytes((result as { image: string }).image);
  }
  throw new Error('Unexpected Workers AI image-generation response shape');
}

/**
 * FLUX.1 [schnell] on Workers AI. Always configured (the `AI` binding is always
 * present), so it is the universal fallback and the only provider that runs under
 * local `wrangler dev` with no external keys.
 */
export const fluxProvider: ImageProvider = {
  id: 'flux',
  isConfigured: () => true,
  async generate(prompt, env) {
    const result = await env.AI.run(FLUX_MODEL, { prompt });
    return { bytes: await workersAiToBytes(result), modelLabel: FLUX_LABEL };
  },
};

/** Sleep helper for bounded polling (Workers provide setTimeout). */
function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/** The WaveSpeed task envelope (`data`) we read from submit + poll responses. */
interface WavespeedTask {
  id?: string;
  status?: 'created' | 'queued' | 'processing' | 'completed' | 'failed';
  error?: string;
  urls?: { get?: string };
  outputs?: string[];
}
interface WavespeedResponse {
  data?: WavespeedTask;
}

/**
 * WaveSpeedAI image provider (api.wavespeed.ai). Submit-then-poll:
 *   POST /api/v3/{model}  { prompt }            -> { data: { id, urls.get } }
 *   GET  data.urls.get    (poll)                -> { data: { status, outputs[] } }
 * then the first `outputs` URL is fetched for the PNG bytes.
 *
 * Configured only when WAVESPEED_API_KEY is set (otherwise the chain falls back to
 * FLUX). The model id comes from WAVESPEED_MODEL (default {@link WAVESPEED_DEFAULT_MODEL}).
 * `fetchImpl` + poll timing are injectable so tests drive it without network or delay.
 *
 * ANONYMITY: only the static dish prompt is sent — no user data — so the provider's
 * region/retention is not GDPR-relevant for this plane (SECURITY.md §1).
 */
export function makeWavespeedProvider(
  fetchImpl: typeof fetch = globalThis.fetch,
  opts: { pollDelayMs?: number; maxPolls?: number; extraParams?: Record<string, unknown> } = {},
): ImageProvider {
  const pollDelayMs = opts.pollDelayMs ?? 800;
  const maxPolls = opts.maxPolls ?? 40;
  // Extra generation params merged into the submit body (e.g. { size: '1024*1024' })
  // so output dimensions/quality are controlled and identical across models. Never
  // carries user data — purely generation settings.
  const extraParams = opts.extraParams ?? {};

  return {
    id: 'wavespeed',
    isConfigured: (env) =>
      typeof env.WAVESPEED_API_KEY === 'string' && env.WAVESPEED_API_KEY.length > 0,
    async generate(prompt, env) {
      const key = env.WAVESPEED_API_KEY;
      if (!key) throw new Error('WaveSpeed provider is not configured');
      const model = env.WAVESPEED_MODEL && env.WAVESPEED_MODEL.length > 0
        ? env.WAVESPEED_MODEL
        : WAVESPEED_DEFAULT_MODEL;
      const auth = { Authorization: `Bearer ${key}` };

      // 1. Submit the task.
      const submit = await fetchImpl(`${WAVESPEED_BASE_URL}/${model}`, {
        method: 'POST',
        headers: { ...auth, 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt, ...extraParams }),
      });
      if (!submit.ok) throw new Error(`WaveSpeed submit returned HTTP ${submit.status}`);
      const submitted = (await submit.json()) as WavespeedResponse;
      const task = submitted.data;
      const pollUrl = task?.urls?.get
        ?? (task?.id ? `${WAVESPEED_BASE_URL}/predictions/${task.id}` : undefined);
      if (!pollUrl) throw new Error('WaveSpeed submit returned no task id / poll URL');

      // 2. Poll until completed (or failed / exhausted).
      let outputs: string[] | undefined = task?.status === 'completed' ? task.outputs : undefined;
      if (!outputs) {
        for (let i = 0; i < maxPolls; i += 1) {
          await sleep(pollDelayMs);
          const res = await fetchImpl(pollUrl, { headers: auth });
          if (!res.ok) throw new Error(`WaveSpeed poll returned HTTP ${res.status}`);
          const polled = ((await res.json()) as WavespeedResponse).data;
          if (polled?.status === 'failed') {
            throw new Error(`WaveSpeed task failed: ${polled.error ?? 'unknown error'}`);
          }
          if (polled?.status === 'completed') {
            outputs = polled.outputs;
            break;
          }
        }
      }
      const imageUrl = outputs?.[0];
      if (typeof imageUrl !== 'string' || imageUrl.length === 0) {
        throw new Error('WaveSpeed produced no output image (timed out or empty)');
      }

      // 3. Fetch the produced image bytes.
      const img = await fetchImpl(imageUrl);
      if (!img.ok) throw new Error(`WaveSpeed image fetch returned HTTP ${img.status}`);
      const bytes = new Uint8Array(await img.arrayBuffer());
      return { bytes, modelLabel: `wavespeed:${model}` };
    },
  };
}

/** The shape of the Vertex `:predict` response field we consume (parsed defensively). */
interface VertexPredictResponse {
  predictions?: Array<{ bytesBase64Encoded?: string }>;
}

/**
 * Imagen 4 Fast on Vertex AI, called in an EU region. Configured only when a
 * project id, region, and access token are all present — otherwise the route
 * falls back to FLUX. The HTTP call is injectable for tests (no network in tests).
 */
export function makeImagenProvider(
  fetchImpl: typeof fetch = globalThis.fetch,
): ImageProvider {
  return {
    id: 'imagen',
    isConfigured: (env) =>
      typeof env.VERTEX_PROJECT_ID === 'string' &&
      env.VERTEX_PROJECT_ID.length > 0 &&
      typeof env.VERTEX_LOCATION === 'string' &&
      env.VERTEX_LOCATION.length > 0 &&
      typeof env.VERTEX_ACCESS_TOKEN === 'string' &&
      env.VERTEX_ACCESS_TOKEN.length > 0,
    async generate(prompt, env) {
      const project = env.VERTEX_PROJECT_ID;
      const location = env.VERTEX_LOCATION;
      const token = env.VERTEX_ACCESS_TOKEN;
      if (!project || !location || !token) {
        // Guarded by isConfigured(); defensive so a misuse fails loudly, not silently.
        throw new Error('Imagen provider is not configured');
      }

      const endpoint =
        `https://${location}-aiplatform.googleapis.com/v1/projects/${project}` +
        `/locations/${location}/publishers/google/models/${IMAGEN_MODEL}:predict`;

      const res = await fetchImpl(endpoint, {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${token}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          instances: [{ prompt }],
          parameters: { sampleCount: 1, aspectRatio: '1:1' },
        }),
      });

      if (!res.ok) {
        throw new Error(`Vertex Imagen returned HTTP ${res.status}`);
      }

      const json = (await res.json()) as VertexPredictResponse;
      const b64 = json.predictions?.[0]?.bytesBase64Encoded;
      if (typeof b64 !== 'string' || b64.length === 0) {
        throw new Error('Vertex Imagen returned no image bytes');
      }
      return { bytes: base64ToBytes(b64), modelLabel: IMAGEN_LABEL };
    },
  };
}

/** Knobs for the WaveSpeed provider: polling cadence (tests use no delay) + extra
 *  generation params merged into the submit body (e.g. { size, enable_sync_mode }). */
export interface WavespeedPollOpts {
  pollDelayMs?: number;
  maxPolls?: number;
  extraParams?: Record<string, unknown>;
}

/**
 * Build the ordered provider chain for this env: the preferred provider first
 * (IMAGE_PROVIDER), then the remaining ones as fallbacks. FLUX is always present and
 * always last by default because it is always configured. `fetchImpl` is injectable
 * (shared by the WaveSpeed + Imagen HTTP calls) so tests drive them without network.
 */
export function buildProviderChain(
  env: Env,
  fetchImpl: typeof fetch = globalThis.fetch,
  wavespeedOpts?: WavespeedPollOpts,
): ImageProvider[] {
  // Production generation params for WaveSpeed, derived from env: a fixed output
  // size (faster/lighter/cheaper) + sync mode (result returns inline, no polling).
  // Explicit opts.extraParams (e.g. from a comparison test) win over the env ones.
  const envExtra: Record<string, unknown> = env.WAVESPEED_IMAGE_SIZE
    ? { size: env.WAVESPEED_IMAGE_SIZE, enable_sync_mode: true }
    : {};
  const wsOpts = {
    ...wavespeedOpts,
    extraParams: { ...envExtra, ...(wavespeedOpts?.extraParams ?? {}) },
  };

  const byId: Record<ImageProviderId, ImageProvider> = {
    wavespeed: makeWavespeedProvider(fetchImpl, wsOpts),
    imagen: makeImagenProvider(fetchImpl),
    flux: fluxProvider,
  };
  // Historical default favours Imagen, then WaveSpeed, then the on-platform FLUX.
  const defaultOrder: ImageProviderId[] = ['imagen', 'wavespeed', 'flux'];
  const pref = env.IMAGE_PROVIDER;
  const order: ImageProviderId[] = pref
    ? [pref, ...defaultOrder.filter((id) => id !== pref)]
    : defaultOrder;
  // Keep only providers that can actually run in this env (creds/bindings present).
  // FLUX is always configured, so the chain is never empty.
  return order.map((id) => byId[id]).filter((p) => p.isConfigured(env));
}

/**
 * Run the provider chain: try each configured provider in order, falling back to
 * the next on failure. Throws only if EVERY provider failed.
 */
export async function generateWithFallback(
  prompt: string,
  env: Env,
  fetchImpl: typeof fetch = globalThis.fetch,
  wavespeedOpts?: WavespeedPollOpts,
): Promise<GeneratedImage> {
  const chain = buildProviderChain(env, fetchImpl, wavespeedOpts);
  let lastError: unknown;
  for (const provider of chain) {
    try {
      return await provider.generate(prompt, env);
    } catch (err) {
      lastError = err;
    }
  }
  throw new Error('All image providers failed', { cause: lastError });
}
